part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const TABS = _Paths.TABS;
  // static const HOME = _Paths.HOME;
  // static const CATEGORY = _Paths.CATEGORY;
  // static const SERVICE = _Paths.SERVICE;
  static const CART = _Paths.CART;
  // static const ME = _Paths.ME;
  static const REGISTER = _Paths.REGISTER;
  static const REGISTER_CODE = _Paths.REGISTER_CODE;
  static const REGISTER_PASSWORD = _Paths.REGISTER_PASSWORD;
  static const LOGIN = _Paths.LOGIN;
  static const VERIFICATION_CODE_LOGIN = _Paths.VERIFICATION_CODE_LOGIN;
  static const VERIFICATION_CODE = _Paths.VERIFICATION_CODE;
  static const ACCOUNT_PASSWORD_LOGIN = _Paths.ACCOUNT_PASSWORD_LOGIN;
  static const ONE_CLICK_LOGIN = _Paths.ONE_CLICK_LOGIN;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const ACCOUNT_HELP = _Paths.ACCOUNT_HELP;
  static const SEARCH = _Paths.SEARCH;
  static const GOODS_LIST = _Paths.GOODS_LIST;
  static const GOODS_CONTENT = _Paths.GOODS_CONTENT;
  static const CUSTOMER_SERVICE = _Paths.CUSTOMER_SERVICE;
  static const OFFICIAL_SERVICE = _Paths.OFFICIAL_SERVICE;
  static const SETTING = _Paths.SETTING;
  static const PROFILE = _Paths.PROFILE;
  static const VIP_CODE = _Paths.VIP_CODE;
  static const MESSAGE_NOTIFICATION = _Paths.MESSAGE_NOTIFICATION;
  static const MESSAGE = _Paths.MESSAGE;
  static const VIP_MEDAL = _Paths.VIP_MEDAL;
  static const CHECKOUT = _Paths.CHECKOUT;
  static const ADDRESS_MANAGER = _Paths.ADDRESS_MANAGER;
  static const ADDRESS_CREATE = _Paths.ADDRESS_CREATE;
  static const ADDRESS_MODIFY = _Paths.ADDRESS_MODIFY;
  static const PERSONAL_HOMEPAGE = _Paths.PERSONAL_HOMEPAGE;
  static const PAYMENT = _Paths.PAYMENT;
  static const ORDER_LIST = _Paths.ORDER_LIST;
  static const ORDER_INFO = _Paths.ORDER_INFO;
  static const ORDER_CONTENT = _Paths.ORDER_CONTENT;
  static const AFTER_SALE = _Paths.AFTER_SALE;
  static const THEME = _Paths.THEME;
  static const WEB = _Paths.WEB;
}

abstract class _Paths {
  _Paths._();
  static const TABS = '/tabs';
  // static const HOME = '/home';
  // static const CATEGORY = '/category';
  // static const SERVICE = '/service';
  static const CART = '/cart';
  // static const ME = '/me';
  static const REGISTER = '/register';
  static const REGISTER_CODE = '/register-code';
  static const REGISTER_PASSWORD = '/register-password';
  static const LOGIN = '/login';
  static const VERIFICATION_CODE_LOGIN = '/verification-code-login';
  static const VERIFICATION_CODE = '/verification-code';
  static const ACCOUNT_PASSWORD_LOGIN = '/account-password-login';
  static const ONE_CLICK_LOGIN = '/one-click-login';
  static const RESET_PASSWORD = '/reset-password';
  static const ACCOUNT_HELP = '/account-help';
  static const SEARCH = '/search';
  static const GOODS_LIST = '/goods-list';
  static const GOODS_CONTENT = '/goods-content';
  static const CUSTOMER_SERVICE = '/customer-service';
  static const OFFICIAL_SERVICE = '/official-service';
  static const SETTING = '/setting';
  static const PROFILE = '/profile';
  static const VIP_CODE = '/vip-code';
  static const MESSAGE_NOTIFICATION = '/message-notification';
  static const MESSAGE = '/message';
  static const VIP_MEDAL = '/vip-medal';
  static const CHECKOUT = '/checkout';
  static const ADDRESS_MANAGER = '/address-manager';
  static const ADDRESS_CREATE = '/address-create';
  static const ADDRESS_MODIFY = '/address-modify';
  static const PERSONAL_HOMEPAGE = '/personal-homepage';
  static const PAYMENT = '/payment';
  static const ORDER_LIST = '/order-list';
  static const ORDER_INFO = '/order-info';
  static const ORDER_CONTENT = '/order-content';
  static const AFTER_SALE = '/after-sale';
  static const THEME = '/theme';
  static const WEB = '/web';
}
